spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://cheerio_pk_admin:Rn02wd8X3NFBPuWQ@cheerio-a5eg4.mongodb.net/cheerio_db?retryWrites=true

servers:
  auth-service:
    address: https://foio-auth-service.herokuapp.com
    login:
      uri: /oauth/token
      authorization: Basic Zm9pb19hdXRoX3NlcnZpY2U6NzBmTmRPTG1sS1pNZnBEYTlLQ1YvaUdCL2ZmN3hrMldPNXc4WFNlTURkYz0=
    register:
      uri: /users
      authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjMxMzIxNTg3NjUsInVzZXJfbmFtZSI6ImZvaW9fYXBpIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BVVRIX0NSRUFURV9VU0VSIl0sImp0aSI6ImJkNTdhNmRlLTcyZGYtNDAyZS1iN2NkLTVmNjU3ZjI5YTFkZiIsImNsaWVudF9pZCI6ImZvaW9fYXV0aF9zZXJ2aWNlIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.xt1vgrB8clS5rTav6x0oBmTtqaGg51NOcns_WYaoIU1aJO5pnb6byCfcz4T7XsgRy4bZTWXf_Jmu3PHFBmbI_wwS8zfeaR2vD1ijn6qX5aKY9dJ2yscll1xhFKlSJpHSgEReUMDU9hft9gIjEz5ife4NUmH5KGsH0u0xgmUaoNOtMNJZZG4usTt4QLwBXawocLd0X8-WP6bb-xTHNbr5DkqkTS3cSClK4xjbEW-E0nlSFY8-RAfEBKbAvfynR40sB4VDE_8j-uSQyGxxAWHgMkBGGwNHwXtPqwEyWpamO7q2LIDZH4RuFVWEUo6QNtD3KzU26Mp8sSft2Gk5jUeR4A